### ISSUE TITLE
Complete the resources page

### ISSUE THREAD

**Issue by Hareesh-Nandigrama** [swciitg/swc_website#21]
Add the resources page as shown in the figma link below
https://www.figma.com/file/tm1D7uXp6qCp5DvVghcsq7/SWC_Website?type=design&node-id=1678%3A998&mode=design&t=NqCZDaLNxZT0diV9-1

**Comment by kvineet002** [comment]
Assign this to me.

**Comment by Hareesh-Nandigrama** [comment]
You have been assigned @kvineet002

**Comment by kvineet002** [comment]
@Hareesh-Nandigrama The provided figma file looks old!Please look into that!!

**Comment by Hareesh-Nandigrama** [comment]
The design provided in the link is required, make appropriate changes to match with the new design
