### ISSUE TITLE
Add Resource links to the resources page

### ISSUE THREAD

**Issue by Sofiyana-1811** [swciitg/swc_website#24]
please add the following links to the resources pages buttons - 
HTML/CSS/Js: https://swciitg.notion.site/Hackstack-Html-css-js-2023-27109c6b9f2b48a4ac5ecc7bde687570
NodeJs: https://swciitg.notion.site/Node-js-Workshop-2023-HackStack-268dcbe21f8b45fc9016320ddd10aa2f
ReactJs: https://swciitg.notion.site/React-js-Workshop-2023-HackStack-9e75bc6fa7664e45930074ad11cab317
Flutter: https://www.notion.so/swciitg/Flutter-Workshop-2023-58e463347af34fb9be6f1d5dc06fb26e?pvs=4
UI/UX: https://www.notion.so/swciitg/54316871381e4f3abafaacf967e22d41?v=604ac080329c4adfab7a5ea4bb03890d&pvs=4

**Comment by dhaneshragu** [comment]
please assign it to me. i want to work on this.

**Comment by kvineet002** [comment]
@Sofiyana-1811 I had made the resources page so i know where to put the links. if @dhaneshragu agree to give their task to me. Please assign me.
