### ISSUE TITLE
Add AdminJS Portal for Admin Dashboard

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/swc_website#32]
This issue involves integrating AdminJS into the backend and setting up basic configurations to manage our models through the portal.

Goal:

The goal is to provide an intuitive admin interface for administrators to manage data without needing to interact directly with the database. It will allow CRUD (Create, Read, Update, Delete) operations on existing models, such as users, tasks, and any other necessary entities in our system.

**Comment by heet434** [comment]
I'm ready to work on the issue, please assign me @Ashmit-Verma

**Comment by Srayash** [comment]
hey @Ashmit-Verma can i work on this?

**Comment by Ashmit-Verma** [comment]
> I'm ready to work on the issue, please assign me @Ashmit-Verma

assigned to you @heet434

**Comment by Ashmit-Verma** [comment]
> hey @Ashmit-Verma can i work on this?

please look at issues on other repos like intranetsearch

**Comment by Ashmit-Verma** [comment]
> > I'm ready to work on the issue, please assign me @Ashmit-Verma
> 
> assigned to you @heet434

updates ?

**Comment by heet434** [comment]
> > > I'm ready to work on the issue, please assign me @Ashmit-Verma
> > 
> > assigned to you @heet434
> 
> updates ?
> 

working on it, give me 2-3 days more. Mostly the issue I'm facing is Admin JS doesn't support Next directly, so will have to devise a workaround and make an admin panel using a different template.

**Comment by heet434** [comment]
Fixed by #37
